config/routes.rb
InteractiveImporterDemo::Application.routes.draw do
  resources :people
  delete 'people', :to => 'people#delete_all'

  resources :person_imports
  

end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :first_name, :last_name, :presence => true
end

app/models/person_import.rb
class PersonImport < InteractiveImporter::CsvImport
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.paginate(:page => params[:page])
  end
  
  def delete_all
    Person.delete_all
    redirect_to Person, :notice => "All people where deleted"
  end
end

app/controllers/person_imports_controller.rb
class PersonImportsController < ApplicationController
  def new
    @csv_import = PersonImport.new
  end
  
  def create
    @csv_import = PersonImport.new(params[:person_import])
    if @csv_import.save
      redirect_to @csv_import
    else
      render 'new'
    end
  end
  
  def show
    @csv_import = PersonImport.find(params[:id])
  end
  
  def update
    @csv_import = PersonImport.find(params[:id])
    @csv_import.update_attributes params[:person_import]
    @csv_import.import!
    
    redirect_to Person if @csv_import.csv_rows.count(:conditions => {:state => 'error'}).zero?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/csv_imports/show.html.erb
<h1>Importing <%= @csv_import.file_name %></h1>
<%= form_for @csv_import do |form| %>
  <table>
    <% @csv_import.file_columns.each_with_index do |column, index| %>
      <th><%= select_tag "csv_import[columns][]", options_for_select([""] + @csv_import.importable_columns) %></th>
    <% end %>
    <% @csv_import.file_rows.each do |row| %>
      <tr>
        <% row.each do |cell| %>
          <td><%= cell %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= form.submit 'Import' %>
<% end %>

app/views/csv_imports/update.html.erb
<h1>Importing Errors</h1>
<p>The following rows could not be imported due to errors</p>
<%= form_for @csv_import do |form| %>
  <table>
    <tr>
      <th>Row Number</th>
      <% @csv_import.columns.each do |column| %>
        <th><%= select_tag "csv_import[columns][]", options_for_select([""] + @csv_import.importable_columns, column) %></th>
      <% end %>
      <th>Delete</th>
    </tr>
    <% form.fields_for :csv_rows, @csv_import.csv_rows.reject(&:destroyed?) do |row_fields| %>
      <tr>
        <td><%= row_fields.object.number + 1 %><%= row_fields.hidden_field :id %></td>
        <% @csv_import.columns.each_with_index do |column, index| %>
          <td valign='top'>
            <%= text_field_tag "#{row_fields.object_name}[content][]", row_fields.object.content[index], :class => row_fields.object.errors[column].present? ? 'error' : nil %>
            <% if row_fields.object.errors[column].present? %>
              <div class='error'><%= row_fields.object.errors[column].to_a.join(', ') %></div>
            <% end %>
          </td>
        <% end %>
        <td><%= row_fields.check_box :_destroy %></td>
      </tr>
    <% end %>
  </table>
  <%= form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InteractiveImporterDemo</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <%= flash[:notice]%>
    <%= yield %>
  </body>
</html>

app/views/people/index.html.erb
<h1>People</h1>
<% if @people.any? %>
  <table>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
    </tr>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.email %></td>
      </tr>  
    <% end %>
  </table>
  <%= will_paginate @people %>
  <%= link_to 'Delete all', people_path, :method => :delete %>
<% end %>
<%= link_to 'Import', new_person_import_path %>
  

app/views/person_imports/new.html.erb
<%= form_for @csv_import, :html => {:multipart => true} do |form| %>
  <div class='field'>
    <%= form.label :file %>
    <%= form.file_field :file %>
    <%= @csv_import.errors[:file].join(', ') %>
  </div>
  <%= form.submit %>
<% end %>

app/views/person_imports/show.html.erb
<h1>Importing <%= @csv_import.file_name %></h1>
<%= form_for @csv_import do |form| %>
  <table>
    <% @csv_import.file_columns.each_with_index do |column, index| %>
      <th><%= form.column_select column %></th>
    <% end %>
    <% @csv_import.file_rows.each do |row| %>
      <tr>
        <% row.each do |cell| %>
          <td><%= cell %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= form.submit 'Import' %>
<% end %>

app/views/person_imports/update.html.erb
<h1>Importing Errors</h1>
<p>The following rows could not be imported due to errors</p>
<%= form_for @csv_import do |form| %>
  <table>
    <tr>
      <th>Row Number</th>
      <% @csv_import.columns.each do |column| %>
        <th><%= form.column_select column %></th>
      <% end %>
      <th>Delete</th>
    </tr>
    <% form.fields_for :csv_rows, @csv_import.csv_rows.to_a.select{|r| r.state == 'error' } do |row_fields| %>
      <tr>
        <td><%= row_fields.object.number + 1 %><%= row_fields.hidden_field :id %></td>
        <% @csv_import.columns.each_with_index do |column, index| %>
          <td valign='top'>
            <%= row_fields.cell_text_field index, :class => row_fields.object.errors[column].present? ? 'error' : nil %>
            <% if row_fields.object.errors[column].present? %>
              <div class='error'><%= row_fields.object. errors[column].to_a.join(', ') %></div>
            <% end %>
          </td>
        <% end %>
        <td><%= row_fields.check_box :_destroy %></td>
      </tr>
    <% end %>
  </table>
  <%= form.submit %>
<% end %>